- id: '1694788289546'
  alias: Garage Door announcement
  description: This is the description
  trigger:
  - type: opened
    platform: device
    device_id: d10f1fc0070690d390d20b635b4c0180
    entity_id: e77f7f1848f4af2316530a03b38eb06e
    domain: binary_sensor
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.downstairs_speaker
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
      media_content_type: provider
    metadata:
      title: The garage door is opening
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
  - service: media_player.play_media
    target:
      entity_id: media_player.office_display
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
      media_content_type: provider
    metadata:
      title: The garage door is opening
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
  - service: notify.discord_home_assistant
    data:
      message: The Garage Door is opening
      target:
      - '1151470003808374794'
  mode: single
