- id: '1694788289546'
  alias: Garage Door announcement
  description: This is the description
  trigger:
  - type: opened
    platform: device
    device_id: d10f1fc0070690d390d20b635b4c0180
    entity_id: e77f7f1848f4af2316530a03b38eb06e
    domain: binary_sensor
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.downstairs_speaker
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
      media_content_type: provider
    metadata:
      title: The garage door is opening
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
  - service: media_player.play_media
    target:
      entity_id: media_player.office_display
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
      media_content_type: provider
    metadata:
      title: The garage door is opening
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+garage+door+is+opening&language=en-us
  - service: notify.discord_home_assistant
    data:
      message: The Garage Door is opening
      target:
      - '1151470003808374794'
  mode: single
- id: '1695065601516'
  alias: Push To Github
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: shell_command.push_updates_to_github
    data: {}
  mode: single
- id: '1695484154403'
  alias: Reset Washer
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 6174f2292b0ce3e1390d41a944c0f042
    entity_id: d2ca10107154a2fda2d29bfb73d77d62
    domain: binary_sensor
  - platform: state
    entity_id:
    - binary_sensor.washer_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: house/washer/status
      payload: idle
  - service: script.turn_off
    data: {}
    target:
      entity_id: script.washer_finished_notification_audible
  mode: single
- id: '1695496404493'
  alias: Washer Running
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    above: 3
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.washer_status
      state: idle
    - condition: state
      entity_id: sensor.washer_status
      state: complete
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: house/washer/status
      payload: running
  mode: single
- id: washer_completed
  alias: Washer Complete
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 3
  condition:
  - condition: state
    entity_id: sensor.washer_status
    state: running
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: house/washer/status
      payload: complete
  - service: mqtt.publish
    data:
      retain: true
      topic: house/washer/time_complete
      payload: '{{ now().timestamp() }}'
  - service: notify.discord_home_assistant
    metadata: {}
    data:
      target:
      - '1151470003808374794'
      message: The Washer is Complete!
  mode: single
- id: '1695497554668'
  alias: Washer Notify
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.washer_status
    from: running
    to: complete
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.office_display
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+washer+is+complete&language=en-us
      media_content_type: provider
    metadata:
      title: The washer is complete
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+washer+is+complete&language=en-us
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.washer_finished_notification_audible
  mode: single
- id: '1695848014900'
  alias: Meeting Start
  description: ''
  trigger:
  - platform: state
    entity_id:
    - calendar.daniel_revunit_com
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 0
      - 0
    target:
      area_id: office
  mode: single
- id: '1695849901023'
  alias: Meeting Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - calendar.daniel_revunit_com
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.office_status_light_light
  mode: single
- id: '1695908614236'
  alias: Front Door
  description: ''
  trigger:
  - platform: device
    device_id: 0946b7ec84caf897a3ce2ba9ca9ede12
    domain: nest
    type: camera_person
  condition: []
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.front_door_light
  mode: single
- id: '1700084464187'
  alias: Christmas Tree - Evening - On
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: 2bb93c4f3bca761b68e02ae4b87bfe5e
    entity_id: d18294ef164de2ca5d601ef3781d08a1
    domain: switch
  mode: single
- id: '1700084497804'
  alias: Christmas Tree - Evening- Off
  description: ''
  trigger:
  - platform: time
    at: '20:15:00'
  condition: []
  action:
  - type: turn_off
    device_id: 2bb93c4f3bca761b68e02ae4b87bfe5e
    entity_id: d18294ef164de2ca5d601ef3781d08a1
    domain: switch
  mode: single
- id: '1700513864945'
  alias: Mail Open
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: e50468eca04ce6bdb852703dda6a435a
    entity_id: d329a69b0f62aeb444c6cd07248022dc
    domain: binary_sensor
  condition: []
  action:
  - service: notify.discord_home_assistant
    data:
      message: MAIL!
      target:
      - '1151470003808374794'
  mode: single
- id: '1700663887894'
  alias: Christmas Tree - Morning - On
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - type: turn_on
    device_id: 2bb93c4f3bca761b68e02ae4b87bfe5e
    entity_id: d18294ef164de2ca5d601ef3781d08a1
    domain: switch
  mode: single
- id: '1700663920495'
  alias: Christmas Tree - Morning - Off
  description: ''
  trigger:
  - platform: time
    at: 08:15:00
  condition: []
  action:
  - type: turn_off
    device_id: 2bb93c4f3bca761b68e02ae4b87bfe5e
    entity_id: d18294ef164de2ca5d601ef3781d08a1
    domain: switch
  mode: single
