# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml

shell_command:
  push_updates_to_github: /bin/bash ha_gitpush.sh

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: password
  max_retries: 3
  default_measurement: state

ics_calendar:
  calendars:
    - name: "JBH"
      url: "https://outlook.office365.com/owa/calendar/9903254c1fd94671b77080e404edbbaf@jbhunt.com/c1132205c90241d0b6db533c0e32d53f11161040605479894425/calendar.ics"
